apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
type: Opaque
data:
  username: YWRtaW4=
  password: UGFzc0AxMjM=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
    - name: app
      image: nginx
      env:
        - name: USERNAME 
          valueFrom: 
            secretKeyRef:
              name: pod-secret
              key: username
        - name: PASSWORD 
          valueFrom: 
            secretKeyRef:
              name: pod-secret
              key: password