---
- name: Launch EC2 instance
  hosts: localhost
  connection: local 
  gather_facts: false

  vars_files: 
    - group_vars/all.yml
  tasks:
    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "{{ tag_name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ security_group_name }}"
        image_id: "{{ ami_id }}"
        count: 1
        tags:
          Environment: Testing
          Name: "{{ tag_name }}"
      register: ec2_result
    - name: Output Instance Details
      debug:
        var: ec2_result

    # us-east-1 Linux imageid: ami-0157af9aea2eef346
    # us-east-1 ubuntu imageid: ami-0ecb62995f68bb549

# run playbook: ansible-playbook create_ec2.yml
# to terminate instance using adhoc command: 
# ansible localhost -m amazon.aws.ec2_instance 
# -a "instance_ids=i-00973f26752f46125 state=terminated region=us-east-1"