apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx # you can give anything using this connect pod with service
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
